version: "3.7"
services:
  mongodb:
    container_name: mongodb-crud
    build:
      context: ./db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"